# -*- coding: utf-8 -*-
"""Mosi Tugas 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AU9KNjptFZaGJlxSaHK8c_1Cm7Y2yiwc

NI LUH MADE DITA ANJANI

1301174676

IF-41-04
"""

import random
import statistics
from scipy.stats import norminvgauss

# ALGORITMA 1
N = 100
a = 0
b = 1
arrx = []
arrfx = []
arrvarfa = []


for i in range (N):
  x = random.uniform(a,b)
  arrx.append(x)
  fx = (arrx[i]**2+arrx[i]+5) # f(x) = x**2 + x + 5
  arrfx.append(fx)

i=1
for i in range(N):
  varfa = (arrfx[i] - avgf)**2
  arrvarfa.append(varfa)
avgf = (sum(arrfx))/N
varf = sum(arrvarfa)/(N-1)
avgvarf = varf / N

k = norminvgauss.ppf(0.95, 1, 0)
w1 = (b-a)*(avgf - (k*avgvarf))
w2 = (b-a)*(avgf + (k*avgvarf))

print("Var F : ",varf)
print("Average var f : ", avgvarf)
print(k)
print(w1, "<= I <= ", w2)

# ALGORITMA WAJIB
a = 0
b = 1
M = 100
w = (b-a)/M
arrx=[]
arri = []
for i in range(M):
  xi = a+(i*w)
  arrx.append(xi)
  x = random.uniform(a,b)
  fx = (arrx[i]**2+arrx[i]+5)  # f(x) = x**2 + x + 5
  I = w*(fx)
  arri.append(I)
print(sum(arri))
